#!/bin/sh

count=0
failure=0

for f in $(dirname "$0")/api/*.xml
do
    let count+=1
    test=$(xmllint $f)
    catout=$(cat $f)
    if [ "$test" = "$catout" ]; then
        printf .
    else
        let failure+=1
    fi
done
echo
echo
printf $count\ tests,\ $failure\ failures
echo
echo
